CREATE TABLE IF NOT EXISTS persons (person_id bigint generated by default as identity, first_name varchar(255), last_name varchar(255), primary key (person_id))

CREATE TABLE IF NOT EXISTS addresses (email_address varchar(255) not null, city varchar(255), country varchar(255), person_id bigint, primary key (email_address))

ALTER TABLE addresses ADD CONSTRAINT IF NOT EXISTS person FOREIGN KEY (person_id) REFERENCES persons